- name: Pause module
  hosts: centos3,ubuntu3
  vars:
    pause_for: 10
  tasks:
    - name: "Pause for this many seconds: {{ pause_for }}"
      ansible.builtin.pause:
        seconds: "{{ pause_for }}"
    - name: Pause execution with prompt
      ansible.builtin.pause:
        prompt: 'Check to make sure the server is running, then press enter to continue.'
    - name: Wait for server to run
      ansible.builtin.wait_for:
        port: 80
