- name: Async
  hosts: linux
  vars:
    jobids: []
  tasks:
    - name: Task 1
      ansible.builtin.command: /bin/sleep 10
      changed_when: ansible_hostname != ''
      async: 10
      poll: 0
      register: result1
    - name: Task 2
      ansible.builtin.command: /bin/sleep 10
      changed_when: ansible_hostname != ''
      async: 10
      poll: 0
      register: result2
    - name: Task 3
      ansible.builtin.command: /bin/sleep 10
      changed_when: ansible_hostname != ''
      async: 10
      poll: 0
      register: result3
    - name: Task 4
      ansible.builtin.command: /bin/sleep 10
      changed_when: ansible_hostname != ''
      async: 10
      poll: 0
      register: result4
    - name: Task 5
      ansible.builtin.command: /bin/sleep 10
      changed_when: ansible_hostname != ''
      async: 10
      poll: 0
      register: result5
    - name: Task 6
      ansible.builtin.command: /bin/sleep 10
      changed_when: ansible_hostname != ''
      async: 10
      poll: 0
      register: result6
    - name: Set Job Ids
      ansible.builtin.set_fact:
        jobids: >
                {% if item.ansible_job_id is defined -%}
                  {{ jobids + [item.ansible_job_id] }}
                {% else -%}
                  {{ jobids }}
                {% endif %}
      with_items: "{{ [result1, result2, result3, result4, result5, result6] }}"
    - name: Wait for all jobs
      ansible.builtin.async_status:
        jid: "{{ item }}"
      with_items: "{{ jobids }}"
      register: jobs_result
      until: jobs_result.finished
      retries: 30
