---
- name: Parallel
  hosts: linux
  gather_facts: false
  strategy: free

  tasks:
    - name: Task 1
      ansible.builtin.command: /bin/sleep {{ 10 | random }}
      changed_when: ansible_hostname != ''
    - name: Task 2
      ansible.builtin.command: /bin/sleep {{ 10 | random }}
      changed_when: ansible_hostname != ''
    - name: Task 3
      ansible.builtin.command: /bin/sleep {{ 10 | random }}
      changed_when: ansible_hostname != ''
    - name: Task 4
      ansible.builtin.command: /bin/sleep {{ 10 | random }}
      changed_when: ansible_hostname != ''
    - name: Task 5
      ansible.builtin.command: /bin/sleep {{ 10 | random }}
      changed_when: ansible_hostname != ''
    - name: Task 6
      ansible.builtin.command: /bin/sleep {{ 10 | random }}
      changed_when: ansible_hostname != ''
...
