- name: Looping
  hosts: linux
  tasks:
    - name: Create sequence directories
      ansible.builtin.file:
        dest: /home/james/sequence_{{ item }}
        state: directory
        mode: "0774"
      with_sequence: start=0 end=100 stride=10
    - name: With sequence format
      ansible.builtin.file:
        dest: "{{ item }}"
        state: directory
        mode: "0774"
      with_sequence: start=0 end=100 stride=10 format=/home/james/sequence_%d
    - name: Hex sequence format
      ansible.builtin.file:
        dest: "{{ item }}"
        state: directory
        mode: "0774"
      with_sequence: start=0 end=16 stride=1 format=/home/james/sequence_%x
