- name: Looping
  hosts: linux
  tasks:
    - name: Add users
      ansible.builtin.file:
        dest: /home/{{ item.0 }}/{{ item.1 }}
        owner: "{{ item.0 }}"
        group: "{{ item.0 }}"
        state: directory
        mode: "0774"
      with_together:
        -
          - bob
          - john
        -
          - dance
          - coffe
