- name: Group by distribution
  hosts: linux
  tasks:
    - name: Group centos targets
      ansible.builtin.group_by:
        key: "custom_{{ ansible_distribution | lower }}"
- name: Ping custom_centos group
  hosts: custom_centos
  tasks:
    - name: Ping custom_centos group
      ansible.builtin.ping:
