---
- name: AWS
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create a security group in AWS for SSH access and HTTP
      amazon.aws.ec2_security_group:
        name: ansible
        description: Ansible Security Group
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip:
              - 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip:
              - 0.0.0.0/0
    - name: Provision a set of instances and/or capture existing information
      amazon.aws.ec2_instance:
        name: Ansible
        key_name: ansible
        security_group: ansible
        instance_type: t2.micro
        image_id: ami-0583d8c7a9c35822c
        region: us-east-1
        wait: true
        count: 20
      register: ec2

    - name: Add all instance public IPs to host group
      ansible.builtin.add_host:
        hostname: "{{ item.public_ip_address }}"
        groups:
          - ansiblehosts
        with_items: "{{ ec2.instances }}"

    - name: Show group
      ansible.builtin.debug:
        var: groups.ansiblehosts
...
